remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

Title: Bryce Whitney Project 1 - Introduction
description: A short introduction about myself and a random password generator I created in the past.
